name: Build README table from CSV

on:
  push:
    paths:
      - "data/items.csv"
      - "scripts/build_readme_from_csv.py"
      - ".github/workflows/build-readme.yml"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate README section from CSV
        run: |
          python scripts/build_readme_from_csv.py
          cat README.md
          
      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README table from CSV"
            git push
          else
            echo "No changes to commit."
